version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: ./.env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hmariadb -uroot -p$$(cat /run/secrets/db_root_password) || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: ./.env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wp:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    env_file: ./.env
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html:ro
      - certs:/etc/nginx/certs
    depends_on:
      - wordpress
    networks:
      - inception

networks:
  inception:
    name: inception

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/asadiqui/data/db
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/asadiqui/data/wp
  certs:
    driver: local

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
